#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
把 sdk/src/main/assets 下的脚本文件烘焙成 Java 常量类。

    assets/js/foo.js   ->  ScriptAssets.get("js", "foo")
    assets/py/bar.py   ->  ScriptAssets.get("py", "bar")
    子目录保留: assets/js/sub/a.js -> "sub/a"

生成文件: sdk/gen/com/github/catvod/spider/ScriptAssets.java
（sdk/gen 是编译期源码目录，build.sh 会把它也加进 javac 的源码清单）

为什么要这么做：
  壳是用 DexClassLoader 直接加载 jar 里的 classes.dex 的，jar 内的其它
  条目（assets/js/foo.js）不会进入 ClassLoader 的查找路径，
  getClass().getResourceAsStream() 拿不到。所以编译期把脚本文本烘成
  Java 常量，是唯一在任何壳上都可靠的做法。
"""

import argparse
import os
import sys

CHUNK = 4096  # 每个 Java 字符串常量的最大字符数，避免触及 class 文件 64KB 常量上限

HEADER = """package com.github.catvod.spider;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * AUTO-GENERATED by tools/gen_script_assets.py -- DO NOT EDIT.
 *
 * 内置脚本资源表。脚本源文件位于 sdk/src/main/assets/{js,py}/，
 * 由 build.sh 在编译前调用生成器烘焙进本类。
 */
public final class ScriptAssets {

    public static final String KIND_JS = "js";
    public static final String KIND_PY = "py";

    private static final Map<String, String> SOURCES = new HashMap<String, String>();
    private static final Map<String, List<String>> NAMES = new HashMap<String, List<String>>();

    private ScriptAssets() {}

    private static void register(String kind, String name, String source) {
        SOURCES.put(kind + ":" + name, source);
        List<String> list = NAMES.get(kind);
        if (list == null) {
            list = new ArrayList<String>();
            NAMES.put(kind, list);
        }
        if (!list.contains(name)) list.add(name);
    }

    /** 取脚本源码，没有则返回 null。kind: js / py，name: 不含扩展名的相对路径 */
    public static String get(String kind, String name) {
        if (kind == null || name == null) return null;
        return SOURCES.get(kind + ":" + name);
    }

    /** 某类脚本的全部名字（保持目录扫描顺序） */
    public static List<String> names(String kind) {
        List<String> list = NAMES.get(kind);
        if (list == null) return new ArrayList<String>();
        return new ArrayList<String>(list);
    }

    public static int count() {
        return SOURCES.size();
    }
"""


def java_escape(text):
    """转成 Java 字符串字面量内容。非 ASCII 一律 \\uXXXX，保证生成文件是纯 ASCII。"""
    out = []
    for ch in text:
        code = ord(ch)
        if ch == '\\':
            out.append('\\\\')
        elif ch == '"':
            out.append('\\"')
        elif ch == '\n':
            out.append('\\n')
        elif ch == '\r':
            out.append('\\r')
        elif ch == '\t':
            out.append('\\t')
        elif code < 0x20 or code > 0x7E:
            # 注意: \\u000a \\u000d \\u0022 \\u005c 已在上面分流，不会被生成
            out.append('\\u%04x' % code)
        else:
            out.append(ch)
    return ''.join(out)


def collect(assets_dir, kind, ext):
    """返回 [(name, path)]，name 是去掉扩展名的相对路径（用 / 分隔）"""
    root = os.path.join(assets_dir, kind)
    found = []
    if not os.path.isdir(root):
        return found
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames.sort()
        for fn in sorted(filenames):
            if not fn.endswith(ext):
                continue
            full = os.path.join(dirpath, fn)
            rel = os.path.relpath(full, root)
            rel = rel.replace(os.sep, '/')
            name = rel[: -len(ext)]
            found.append((name, full))
    return found


def read_text(path):
    with open(path, 'r', encoding='utf-8') as f:
        return f.read()


def emit_source_method(index, text):
    """把一个脚本源码切成多个常量，用 StringBuilder 拼起来返回。"""
    lines = []
    lines.append('    private static String src%d() {' % index)
    lines.append('        StringBuilder sb = new StringBuilder();')
    chunks = [text[i:i + CHUNK] for i in range(0, len(text), CHUNK)] or ['']
    for ch in chunks:
        lines.append('        sb.append("%s");' % java_escape(ch))
    lines.append('        return sb.toString();')
    lines.append('    }')
    return lines


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    ap = argparse.ArgumentParser()
    ap.add_argument('--assets', default=os.path.join(here, '..', 'sdk', 'src', 'main', 'assets'))
    ap.add_argument('--out', default=os.path.join(here, '..', 'sdk', 'gen', 'com', 'github', 'catvod', 'spider'))
    args = ap.parse_args()

    assets = os.path.abspath(args.assets)
    out_dir = os.path.abspath(args.out)

    scripts = []
    for kind, ext in (('js', '.js'), ('py', '.py')):
        for name, path in collect(assets, kind, ext):
            scripts.append((kind, name, path))

    body = []
    regs = []
    methods = []
    for i, (kind, name, path) in enumerate(scripts):
        text = read_text(path)
        methods += emit_source_method(i, text)
        regs.append('        register("%s", "%s", src%d());' % (kind, name, i))

    lines = [HEADER.rstrip('\n')]
    lines.append('')
    lines.append('    static {')
    if regs:
        lines += regs
    else:
        lines.append('        /* no embedded scripts */')
    lines.append('    }')
    lines.append('')
    lines += methods
    lines.append('}')
    lines.append('')

    os.makedirs(out_dir, exist_ok=True)
    out_file = os.path.join(out_dir, 'ScriptAssets.java')
    with open(out_file, 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(lines))

    sys.stdout.write('gen_script_assets: %d script(s) -> %s\n' % (len(scripts), out_file))
    for kind, name, path in scripts:
        sys.stdout.write('  [%s] %s  (%s)\n' % (kind, name, os.path.relpath(path, assets)))


if __name__ == '__main__':
    main()
