#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
为每个内置脚本自动生成一个 csp_ 可用的 Spider 代理类。

    sdk/src/main/scripts/江苏名师课堂.js   ->  Jiangsu.java       (api: csp_Jiangsu)
    sdk/src/main/scripts/在线转本地.py     ->  OnlineToLocal.java  (api: csp_OnlineToLocal)

产出:
    sdk/build/gen/com/github/catvod/spider/*.java   参与 javac 的源码
    sdk/build/res/scripts/...                       ASCII 化后的脚本，用于 jar uf

脚本名不需要改：类名由 manifest.json 指定，或自动从文件名推导。

manifest.json（放在 sdk/src/main/scripts/ 下，可选）:
    {
      "江苏名师课堂.js":       { "class": "Jiangsu" },
      "sub/在线转本地_v6.0.py": { "class": "OnlineToLocal" }
    }
"""

import argparse
import hashlib
import json
import os
import re
import shutil
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, '..'))

JAVA_TPL = '''package com.github.catvod.spider;

/**
 * AUTO-GENERATED by tools/gen_spider_proxy.py -- DO NOT EDIT.
 *
 * 源脚本: %(src)s
 * 站点配置: {"key": "%(api)s", "type": 3, "api": "%(api)s", "ext": "<脚本原本需要的 ext>"}
 *
 * ext 原样透传给宿主 Loader，jar 不做任何解析。
 */
public class %(cls)s extends ScriptProxy {

    @Override
    protected String scriptPath() {
        return %(path)s;
    }
}
'''

# SECURE 模式：真实类改名加 Script 后缀，避免与薄壳里的入口类同名
REAL_TPL = '''package com.github.catvod.spider;

/** AUTO-GENERATED -- DO NOT EDIT. 真实实现（编译进加密 payload，不进薄 dex）。 */
public class %(real)s extends ScriptProxy {

    @Override
    protected String scriptPath() {
        return %(path)s;
    }
}
'''

# SECURE 模式：入口壳，只保留类名，反编译看不到任何逻辑
SECURE_TPL = '''package com.github.catvod.spider;

/**
 * AUTO-GENERATED -- DO NOT EDIT.
 *
 * 入口壳：真实逻辑在加密的 payload 里，反编译这里什么都看不到。
 */
public class %(cls)s extends SecureSpider {

    @Override
    protected String target() {
        return %(target)s;
    }
}
'''

INDEX_TPL = '''package com.github.catvod.spider;

/** AUTO-GENERATED -- DO NOT EDIT. jar 内脚本清单，SECURE 模式下供预释放使用。 */
public final class ScriptIndex {

    public static final String[] PATHS = {
%(items)s
    };

    private ScriptIndex() {}
}
'''

ALIAS_TPL = '''package com.github.catvod.spider;

/**
 * AUTO-GENERATED -- DO NOT EDIT.
 *
 * 兼容类：部分壳不剥离 csp_ 前缀，会把 api 原样当类名加载。
 * api 仍填 %(api)s，壳用哪种方式解析都能命中。
 */
public class %(alias)s extends %(cls)s {
}
'''


def sanitize(name):
    """文件名 -> 合法 Java 类名"""
    base = os.path.splitext(os.path.basename(name))[0]
    cleaned = re.sub(r'[^A-Za-z0-9_]', '', base)
    if not cleaned:
        cleaned = 'Script' + hashlib.md5(base.encode('utf-8')).hexdigest()[:6].upper()
    if cleaned[0].isdigit():
        cleaned = 'S' + cleaned
    return cleaned[0].upper() + cleaned[1:] if cleaned else cleaned


def collect(src_dir):
    """扫描脚本源目录，返回 [(相对路径, 绝对路径)]"""
    found = []
    for dirpath, dirnames, filenames in os.walk(src_dir):
        dirnames[:] = sorted(d for d in dirnames if d != '__pycache__')
        for fn in sorted(filenames):
            if fn == 'manifest.json':
                continue
            if fn.endswith('.js') or fn.endswith('.py'):
                full = os.path.join(dirpath, fn)
                rel = os.path.relpath(full, src_dir).replace(os.sep, '/')
                found.append((rel, full))
    return found


def load_manifest(src_dir):
    path = os.path.join(src_dir, 'manifest.json')
    if not os.path.isfile(path):
        return {}
    try:
        with open(path, encoding='utf-8') as f:
            return json.load(f)
    except Exception as e:  # noqa
        sys.stderr.write('manifest.json 解析失败: %s\n' % e)
        return {}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--src', default=os.path.join(ROOT, 'sdk', 'src', 'main', 'scripts'))
    ap.add_argument('--gen', default=os.path.join(ROOT, 'sdk', 'build', 'gen'))
    ap.add_argument('--res', default=os.path.join(ROOT, 'sdk', 'build', 'res'))
    ap.add_argument('--secure', action='store_true',
                    help='生成加密 dex 方案所需的入口壳 + ScriptIndex')
    args = ap.parse_args()

    src_dir = os.path.abspath(args.src)
    gen_dir = os.path.abspath(args.gen)
    res_dir = os.path.abspath(args.res)

    if not os.path.isdir(src_dir):
        sys.stdout.write('no scripts dir: %s\n' % src_dir)
        return 0

    scripts = collect(src_dir)
    if not scripts:
        sys.stdout.write('no .js/.py under %s\n' % src_dir)
        return 0

    manifest = load_manifest(src_dir)
    java_out = os.path.join(gen_dir, 'com', 'github', 'catvod', 'spider')
    # 清空旧产物，避免从 --secure 切回普通模式时残留 *Script.java / ScriptIndex.java
    if os.path.isdir(java_out):
        for f in os.listdir(java_out):
            if f.endswith('.java'):
                os.remove(os.path.join(java_out, f))
    os.makedirs(java_out, exist_ok=True)
    res_scripts = os.path.join(res_dir, 'scripts')
    if os.path.isdir(res_scripts):
        shutil.rmtree(res_scripts)
    os.makedirs(res_scripts, exist_ok=True)

    used = {}
    rows = []
    index_paths = []
    for rel, full in scripts:
        cfg = manifest.get(rel) or {}
        cls = cfg.get('class') or sanitize(rel)
        if cls in used and used[cls] != rel:
            cls = cls + str(abs(hash(rel)) % 1000)
        used[cls] = rel

        sub = os.path.dirname(rel)
        target_rel = (sub + '/' if sub else '') + cls + os.path.splitext(rel)[1]
        target_abs = os.path.join(res_scripts, target_rel)
        os.makedirs(os.path.dirname(target_abs), exist_ok=True)
        shutil.copyfile(full, target_abs)

        api = 'csp_' + cls
        if args.secure:
            real = cls + 'Script'
            # 真实实现（进 payload）
            with open(os.path.join(java_out, real + '.java'), 'w', encoding='utf-8', newline='\n') as f:
                f.write(REAL_TPL % {'real': real, 'src': rel, 'path': json.dumps(target_rel)})
            # 入口壳（进薄 dex）
            with open(os.path.join(java_out, cls + '.java'), 'w', encoding='utf-8', newline='\n') as f:
                f.write(SECURE_TPL % {'cls': cls, 'api': api,
                                      'target': json.dumps('com.github.catvod.spider.' + real)})
            # 兼容壳：部分壳不剥离 csp_ 前缀
            alias = 'csp_' + cls
            with open(os.path.join(java_out, alias + '.java'), 'w', encoding='utf-8', newline='\n') as f:
                f.write(ALIAS_TPL % {'alias': alias, 'cls': cls, 'api': api})
            rows.append((cls, api, rel, target_rel))
            index_paths.append('scripts/' + target_rel)
        else:
            with open(os.path.join(java_out, cls + '.java'), 'w', encoding='utf-8', newline='\n') as f:
                f.write(JAVA_TPL % {'cls': cls, 'api': api, 'src': rel,
                                    'path': json.dumps(target_rel)})
            alias = 'csp_' + cls
            with open(os.path.join(java_out, alias + '.java'), 'w', encoding='utf-8', newline='\n') as f:
                f.write(ALIAS_TPL % {'alias': alias, 'cls': cls, 'api': api})
            rows.append((cls, api, rel, target_rel))

    if args.secure:
        items = ''.join('        %s,\n' % json.dumps(p) for p in index_paths)
        with open(os.path.join(java_out, 'ScriptIndex.java'), 'w', encoding='utf-8', newline='\n') as f:
            f.write(INDEX_TPL % {'items': items})
        sys.stdout.write('  [secure] 入口壳 + ScriptIndex 已生成\n')

    sys.stdout.write('gen_spider_proxy: %d script(s)\n' % len(rows))
    for cls, api, rel, target in rows:
        sys.stdout.write('  %-22s %-18s %s\n' % (api, '(' + cls + '.java)', rel))
    sys.stdout.write('\n站点 api 填上面第一列的 csp_ 名，ext 填脚本原本需要的内容（原样透传）。\n')
    return 0


if __name__ == '__main__':
    sys.exit(main())
